version: "3"
services:
 posgresdb:
    image: postgres
    restart: always
    volumes:
      - ./dbs:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: USERNAME
      POSTGRES_PASSWORD: PASSWD
    ports:
      - 5432:5432

 adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    depends_on:
      - posgresdb